### ISSUE TITLE
Room Elevations 

### ISSUE THREAD

**Issue by clarkwj** [dnenov/pyChilizer#10]
Hi Team,

Having a issue with the room elevation function
I keep getting the error below, rooms are rectangular, the plan tool works fine its just this one,  is it user error or is it something else?
﻿Also I am running the current version of PyRevit v4.8.10
Thanks, 

Created Elevations for room 61 - ROOM 01

ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:An internal error has occurred.

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\wclarkson\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Elevations.pushbutton\script.py", line 106, in <module>
 File "C:\Users\wclarkson\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Elevations.pushbutton\helper.py", line 295, in set_crop_to_bb
Exception: An internal error has occurred.

Script Executor Traceback:
Autodesk.Revit.Exceptions.InternalException: An internal error has occurred.
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by rastermadre** [comment]
Thank you for reporting the issue.
By the looks of it, you're using an older version of pyChilizer tools. You can update by going to the pyRevit tab > pyRevit > Update
![image](https://user-images.githubusercontent.com/43077096/157005563-75defe84-3323-40ad-a554-4dd2994279e9.png)

Please let us know if the issue persists after the update.
