### ISSUE TITLE
Room Data Sheets - Error

### ISSUE THREAD

**Issue by oldo27** [dnenov/pyChilizer#11]
When I tried to use this tool I got the following error.

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\User\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Data Sheets.pushbutton\script.py", line 51, in <module>
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'UnitType'

Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'UnitType'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

How can it be solved? Can I do something?

Thanks!

Aldo

**Comment by rastermadre** [comment]
Hi, thanks for reporting the issue! 

I believe this was fixed already, can you please check you're using the last build? 

You can update the pyChilizer (and every other) toolbar by going to the pyRevit tab > pyrevit dropdown > Update. 
![image](https://user-images.githubusercontent.com/43077096/157642099-3e514805-21ef-46e2-8d97-9dac933c4638.png)
You can also click 'Reload' for this one or re-open Revit. 

Please let us know if that fixes the issue

**Comment by R00118189** [comment]
Thank you for the great work! I started using it today and noticed some tools throw errors. It may be a workstation or even file dependent so if I could piggyback on this thread running Room Data Sheets fails with the following error 
fresh install updated pyRevit and pyChilizer


```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Store\Dropbox\Dynamo Scripts\pyRevit Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Data Sheets.pushbutton\script.py", line 96, in <module>
 File "C:\Store\Dropbox\Dynamo Scripts\pyRevit Extensions\pyChilizer.extension\lib\pychilizer\units.py", line 42, in correct_input_units
 File "C:\Store\Dropbox\Dynamo Scripts\pyRevit Extensions\pyChilizer.extension\lib\pychilizer\units.py", line 13, in get_int_length_units
Exception: The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.


Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidObjectException: The referenced object is not valid, possibly because it has been deleted from the database, or its creation was undone.
 at Autodesk.Revit.DB.Document.GetUnits()
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
 at IronPython.Compiler.Ast.CallExpression.Invoke0Instruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by dariaivanciucova** [comment]
solved
