### ISSUE TITLE
Room Data and Elevation creation

### ISSUE THREAD

**Issue by clarkwj** [dnenov/pyChilizer#12]
Hi there,

I  have updated the app to the latest version and still having issues with the Room Elevation creation (Room Data also doesn't work seems connected) 
This is the error I keep getting 
Any ideas as too what is happening? 
Thanks

ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:An internal error has occurred.

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\wclarkson\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Data Sheets.pushbutton\script.py", line 270, in <module>
 File "C:\Users\wclarkson\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\lib\pychilizer\geo.py", line 272, in set_crop_to_bb
Exception: An internal error has occurred.

Script Executor Traceback:
Autodesk.Revit.Exceptions.InternalException: An internal error has occurred.
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by clarkwj** [comment]
Hi there,
I have this working now. This issue happens when you have view templates already assigned to the elevation view types, remove this and works a treat. 

Am now getting this error  for creating the individual Plan Views, happens as soon as I select the button. 

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\wclarkson\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Plan View.pushbutton\script.py", line 13, in <module>
AttributeError: 'module' object has no attribute 'select_rooms_filter'


Script Executor Traceback:
System.MissingMemberException: 'module' object has no attribute 'select_rooms_filter'
 at IronPython.Runtime.Operations.PythonOps.ObjectGetAttribute(CodeContext context, Object o, String name)
 at IronPython.Runtime.PythonModule.__getattribute__(CodeContext context, String name)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by jmcouffin** [comment]
@clarkwj I did fixed it in my [PR](https://github.com/dnenov/pyChilizer/pull/9)

@dnenov 
But it might need some more love.

**Comment by dnenov** [comment]
I just merged your PR @jmcouffin - @clarkwj any updates on your side?

**Comment by clarkwj** [comment]
nothing from my end.

**Comment by heinrichboldt** [comment]
﻿Hi, I got this error when try to create Room Elevations, 
﻿its same as for Room Elevations+ 
﻿I use Revit 2020.2.9
some Ideas? 
----
```
Created Elevations for room 1 - Room




ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:Modification of the document is forbidden. Typically, this is because there is no open transaction; consult documentation for Document.IsModified for other possible causes.

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\xxx\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Elevations.pulldown\Room Elevations Plus.pushbutton\script.py", line 88, in <module>
 File "C:\Users\xxxx\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\lib\pychilizer\geo.py", line 246, in set_crop_to_bb
Exception: Modification of the document is forbidden. Typically, this is because there is no open transaction; consult documentation for Document.IsModified for other possible causes.

Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidOperationException: Modification of the document is forbidden. Typically, this is because there is no open transaction; consult documentation for Document.IsModified for other possible causes.
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```
