### ISSUE TITLE
Legend by Filter

### ISSUE THREAD

**Issue by Dromandon** [dnenov/pyChilizer#15]
Have this error when click "select":

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\Mikhail.Davtyan\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Annotate.panel\legends.stack\Legend by Filters.pushbutton\script.py", line 124, in <module>
 File "C:\Users\Mikhail.Davtyan\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Annotate.panel\legends.stack\Legend by Filters.pushbutton\script.py", line 34, in convert_length_to_internal
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'UnitType'

Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'UnitType'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
![image](https://user-images.githubusercontent.com/93605735/185400616-5d58e61c-2613-456f-bfe9-1ea9a3a68151.png)

**Comment by jmcouffin** [comment]
Most probably due to the version of Revit you are using. There has been quite a few changes in the Revit api on this side and the code is probably not fit for your revit version
What version are you using?

**Comment by rastermadre** [comment]
Thanks for reporting, will update soon!
