### ISSUE TITLE
Room Data

### ISSUE THREAD

**Issue by heinrichboldt** [dnenov/pyChilizer#25]
﻿simple room foor walls, few windows, door. 
﻿new saved project. 
selected room,
press finish

error appear, nothing happend

Created Elevations for room 1 - Room

ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.Exception'>:Modification of the document is forbidden. Typically, this is because there is no open transaction; consult documentation for Document.IsModified for other possible causes.

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\xxx\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Project.panel\rooms.stack\Room Elevations.pulldown\Room Elevations Plus.pushbutton\script.py", line 88, in <module>
 File "C:\Users\xxx\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\lib\pychilizer\geo.py", line 246, in set_crop_to_bb
Exception: Modification of the document is forbidden. Typically, this is because there is no open transaction; consult documentation for Document.IsModified for other possible causes.

Script Executor Traceback:
Autodesk.Revit.Exceptions.InvalidOperationException: Modification of the document is forbidden. Typically, this is because there is no open transaction; consult documentation for Document.IsModified for other possible causes.
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by rastermadre** [comment]
Hi @heinrichboldt , 
please update to the last version and try again. I don't know where the Document.IsModified error is coming from, but i've found and fixed some bugs in that tool and it should be working better now.
