### ISSUE TITLE
List Walls not working in 2024

### ISSUE THREAD

**Issue by skehg** [dnenov/pyChilizer#45]
Hi I'm loving the tools, great job!

Below is an error I get when trying to use the List Walls tool from the Template panel.

```
IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\kenta\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Template.panel\template2.stack\List Walls.pushbutton\script.py", line 103, in <module>
TypeError: expected float, got Document


Script Executor Traceback:
Microsoft.Scripting.ArgumentTypeException: expected float, got Document
 at Microsoft.Scripting.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run6[T0,T1,T2,T3,T4,T5,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`6.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)
```

**Comment by dariaivanciucova** [comment]
@skehg  Thanks for spotting, should be solved now
