### ISSUE TITLE
No Attribute 'UnitType' Error

### ISSUE THREAD

**Issue by harecu** [dnenov/pyChilizer#5]
I think the latest update to pyRevit may have messed some things up for pyChilizer, in particular the removal of UnitType. See error text from running List Filled Regions:

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\sdc\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Template.panel\template1.stack\List Filled Regions.pushbutton\script.py", line 49, in <module>
 File "C:\Users\sdc\AppData\Roaming\pyRevit\Extensions\pyChilizer.extension\pyChilizer.tab\Template.panel\template1.stack\List Filled Regions.pushbutton\script.py", line 11, in convert_length_to_internal
AttributeError: 'Autodesk.Revit.DB' object has no attribute 'UnitType'

Script Executor Traceback:
System.MissingMemberException: 'Autodesk.Revit.DB' object has no attribute 'UnitType'
 at IronPython.Runtime.Binding.PythonGetMemberBinder.NamespaceTrackerDelegate.Target(CallSite site, Object self, CodeContext context)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
 at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
 at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
 at PyRevitLabs.PyRevit.Runtime.IronPythonEngine.Execute(ScriptRuntime& runtime)

**Comment by dnenov** [comment]
We are currently updating the affected tools and will publish the fix soon. Thank you for flagging the issue up!

**Comment by rastermadre** [comment]
This commit af290a8 should fix this issue. Thanks!
